name: Bug Report Test
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Hoe kunnen we je contacteren op Discord als we extra informatie nodig zijn?
      placeholder: ex. Misstake#1337
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Wat gebeurde er?
      description: Wat gebeurde er precies, dus welke meldingen zag je, wat zag je in je console, etc?
      placeholder: Vertel ons wat je zag en wat er gebeurde!
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: Wat hoorde er te gebueren?
      description: Wat hoorde er te gebeuren, dus wat zou er normaal moeten gebeuren in plaats van het bovenstaande
      placeholder: Vertel ons wat je verwachte.
  - type: textarea
    id: logs
    attributes:
      label: Relevante log bestanden
      description: Kopieër hier aub relevante logs in, dus als er errors in je console waren aub deze hierin kopiëren, zie [log bestanden](https://tedeapolis.nl/tutorials/#log-bestanden)
      placeholder: Sleep hier je logbestanden heen
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Door deze issue aan te maken ga je akkoord met onze [contributing](https://github.com/Tedeapolis/development/blob/master/CONTIBUTING.md) richtlijnen
      options:
        - label: Ik ga akkoord met de contributing richtlijnen
          required: true
